### ISSUE TITLE
Radiation NBT for unrelated items is breaking Thaumcraft aspects

### ISSUE THREAD

**Issue by theron61** [turbodiesel4598/NuclearCraft#490]
It appears that the changes in 2.1.4a attaching radiation information is breaking Thaumcraft aspects making it unplayable.
This output from ThaumicJEI's aspect json file illustrates the issue:

Pre-2.1.4a:
"aspect": "lux",
    "items": [
      "{id:\"minecraft:glowstone\",Count:30s,Damage:0s}",
Post-2.1.4a:
 "aspect": "lux",
    "items": [
      "{ForgeCaps:{\"nuclearcraft:capability_radiation_source\":{radiationLevel:0.0d,radiationBuffer:0.0d},\"nuclearcraft:capability_default_radiation_resistance\":{radiationResistance:0.0d}},id:\"minecraft:glowstone\",Count:3s,Damage:0s}",

Is there any way I can disable registration of these radiation fields on unrelated items?

**Comment by turbodiesel4598** [comment]
It's not quite as simple as that, because this would still be broken for people who want to play with radiation enabled. Will look for a solution now :)

**Comment by turbodiesel4598** [comment]
@theron61 [Could you see if using this build fixes the problem?](https://www.dropbox.com/s/aqz99zshvdabxs3/NuclearCraft-2.14c-1.12.2.jar?dl=0)

**Comment by turbodiesel4598** [comment]
Should be fixed in the latest build :)

**Comment by theron61** [comment]
It does not appear to be fixed.  I am still not able to see aspects on common items or break them down in the crucible.

**Comment by turbodiesel4598** [comment]
Is this 2.14b or 2.14c?

**Comment by theron61** [comment]
2.14c from Dropbox.  I'll try rebuilding the mod pack and try again.

**Comment by theron61** [comment]
Just tried it with the CurseForge posted copy and it appears to work.  I will keep testing.

**Comment by turbodiesel4598** [comment]
Ok, thanks - if stuff is still broken, then that could be a bit of a problem :P
