### ISSUE TITLE
Right clicking nuclear furnace causes game to crash

### ISSUE THREAD

**Issue by ChlorineX** [turbodiesel4598/NuclearCraft#578]
NC Version: 2.18c
Everytime when I right click a nuclear furnace it would crash. 
Crash report: https://pastebin.com/W3qmenCX

**Comment by turbodiesel4598** [comment]
@ChlorineX Does the bug persist in version 2.18d?

**Comment by HydrogenC** [comment]
I succeeded in opening the furnace’s GUI at first, I attempted to smelt Cf-251 Oxide to Cf-251 using Thorium ingots. When I clicked the furnace to check the progress later, it crashed. I tried to click it several more times, and it kept to crash.

**Comment by turbodiesel4598** [comment]
@HydrogenC Does [this build](https://www.dropbox.com/s/ntv8qa1vby75mte/NuclearCraft-2.18e-1.12.2.jar?dl=0) fix the issue? I still can't recreate it on my side, strangely.

**Comment by turbodiesel4598** [comment]
Fixed in 2.18e ;)

**Comment by ChlorineX** [comment]
It does, thanks a lot. Actually,  even in 2.18c, the bug is still really rare and very hard to reproduce.
