### ISSUE TITLE
Crash on Server Start

### ISSUE THREAD

**Issue by dshadowwolf** [turbodiesel4598/NuclearCraft#79]
On trying to start a server with the latest NuclearCraft it hit a "No Class Def Found" in trying to startup. There is, apparently, a reference to the client-side I18n functionality (net.minecraft.client.resources.I18n) somewhere in nc.config.NCConfig.syncConfig according to the log.

When I've had a chance to actually get an FTP client connected to that server, I'll download the crash log and upload it here.

In the meantime, the first few lines of the stack dump:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NuclearCraft (nuclearcraft)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at nc.config.NCConfig.syncConfig(NCConfig.java:124)
        at nc.config.NCConfig.syncFromFiles(NCConfig.java:110)
        at nc.config.NCConfig.preInit(NCConfig.java:98)
        at nc.NuclearCraft.preInit(NuclearCraft.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Deloyar81** [comment]
I have this issue too.
Hopefully my crashlog will help you.

[crash-2017-04-09_12.34.19-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/908134/crash-2017-04-09_12.34.19-server.txt)

**Comment by turbodiesel4598** [comment]
Yep, my mistake - there are currently two I18n classes in Minecraft, and I rather foolishly went for the wrong one - this should be fixed for the next release :)

**Comment by dshadowwolf** [comment]
Heh, no problem. Ran into this issue myself when trying to clean up all the issues SonarQube/SonarLint pulled up in BaseMetals. Despite the server-side versions being listed as deprecated, there are some places where you have to use them, still.

**Comment by Dovahkiin-Warrior** [comment]
@turbodiesel4598 Can you send me a 1.10.2 version for my modded server please? I'd  be much appreciated since I use bigreactors and since not all the mods I wish to use are 1.11 compatible..

**Comment by Boolyman** [comment]
Is there an ETA on this?  I was not aware this was an issue, and have a pack waiting on this fix.

**Comment by turbodiesel4598** [comment]
I'm about to get a fix up on CurseForge - I'm currently away from home, and TeamViewer's playing up a little, so getting things done is a little fiddly. There are also fixes to the EU emission of the generators and the portable ender chest not opening in 1.10.2.

**Comment by Boolyman** [comment]
Reaaaaallly looking foward to this update.   Thanks for being on top of things.

**Comment by turbodiesel4598** [comment]
I've just uploaded a new version that should fix the I18n issue: https://minecraft.curseforge.com/projects/nuclearcraft-mod/files

**Comment by turbodiesel4598** [comment]
As far as I can tell, the crash has gone - is everyone else's good now?

**Comment by CJL48** [comment]
No, the release that I have still crashes. It's a different message though.
[crash-2017-04-17_21.43.24-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/927139/crash-2017-04-17_21.43.24-client.txt)

**Comment by turbodiesel4598** [comment]
Unfortunately, as far as I can tell, there is no way for me to fix that crash on my end - the game is looking for some configs that aren't there. Deleting the config file should fix the issue.

**Comment by turbodiesel4598** [comment]
Despite what I said above, I will look for a fix to the 'config crash'.

**Comment by CJL48** [comment]
Even without the fix, just knowing that I can fix the problem without an update is good. Thanks for your help.

**Comment by turbodiesel4598** [comment]
[Finally fixed the crash - should not be a problem ever again :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)
